name: Validate & Deploy

on:
  push:
    branches:
      - main

jobs:
  validatebuild:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Clean install npm deps
        run: npm ci

      - name: Type check
        run: npm run type-check

      - name: Build code
        run: npm run build

      - name: Zip code
        run: npm run build-zip

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1

      - name: Deploy Code Artifact
        run: aws lambda update-function-code --function-name express-api --zip-file fileb://build.zip
